name: Build and Test
permissions: read-all
on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was triggered by a ${{ github.event_name }} event."
      - run: echo "Running on OS ${{ runner.os }}"
      - run: echo "Checking out branch ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # pin@v3
      - name: "Run `bazel build`"
        run: |
          bazel build //...
      - name: "Run `bazel test`"
        run: |
          bazel test //...
